env:
  global:
  - DEBUG=*
  - secure: C9e1VB9QCwT6hKk/r5l5/vg301IzmvlOZgVsJA+qUH92IOc+FNeN9wZ0pCo9I06cFmHzwaTzyGM49n3iTihiOjrFykCTrxdXd5p24le9JxSv0DS4w7K1HEPVdN3QNoy6n+08vU7H3esMhcOYX9s3sBh3QYEgPuS05iPu0Qq4WFY=
  - secure: eDLMXb+zhTGXbD8CNtlJ4qPQ1RQqysa/2xLKx3PShELLan0sUOUF9c+bRXdHCfuKZeLSgFxMczYT0sU6ELaWks685vzWeKuDoPZAJu/k+hFH/hI7HJnrKsLh2LbSnvaNkjwurliIAVqimFtmwF+HefNy15KNpIvtWBTMOgGUgnU=
  - secure: tA9x85PZyAQNV0dOb+AArkzpBYIguwNs0F/Sv8/UNSq6ZHgyenOuSG9OFYDZtax4ewgQNrqPTKtaPC+UY/ABC0XhjcG9/8HU8aA+BdUsko26hL92Pn2wU92aio9KdSGck2ivff7VMxzkgqDDfKWSm7Y4zdPbXMgHIkCNUo6vgKI=
  - secure: RXIYqfcomDy9gcLOvcI8k3HlTSd8RLGZaPX40TFG4Sz1PXP4xo0pcu2rzqN/rOKUdkOUStc9o8AczwYCxr9EJ/2ALJex151OHiqENxiaEw5ZQl50NcxVF7q/EUsVqL4lvG/KD+PXoruGN2wwfGYH7/4v0iaZ0um7xP19gNzljCw=
language: node_js
node_js:
- '0.10'
script: npm test
before_script:
- sudo -u postgres psql -c "CREATE ROLE queue LOGIN PASSWORD 'secret'";
- sudo -u postgres psql -c "CREATE DATABASE queue_v1 OWNER queue";
services:
- rabbitmq
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: JNWc7d7z9HNIKFg4RcBa4g/WEBV7HkDoFOxLojqOF6yDyNljtziO/aN4i8at3POJDPDaiRNTasiEzoFLBIOEiqDrwgyKbRSibVfxIZUWROt/+dzrOeh0C3if28OuPGVy3Puo+Q3ieIYrJ9pylIuQyQzB6h3H13dKpY3tcPVLVPU=
  app: queue-taskcluster-net
  on:
    repo: taskcluster/taskcluster-queue
